import type { ContentDoc } from "@/content/types";

export const hearsayTemplates: ContentDoc[] = [
  {
    "title": "Hearsay (Criminal) — Answer Template",
    "body": "# Victorian Bar Exam – Hearsay (Criminal) Template\n## 1. Identify the Issue\nIs the evidence a previous representation being adduced to prove the truth of what was asserted? If yes → hearsay rule applies (s59).\n## 2. Is it hearsay? (s59)\nRule: Evidence of a previous representation is inadmissible to prove the existence of a fact asserted unless an exception applies. Authority: Lee v The Queen (1998) 195 CLR 594 (danger of using prior statements to substitute for in-court evidence).\n## 3. Exceptions (Criminal Focus)\n- Maker unavailable (s65): Must be first-hand hearsay; circumstances must make statement reliable (s65(2)); e.g., dying declarations, statements against interest.\n- Maker available & called (s66): Prior representation admissible if fresh in memory or to rebut recent fabrication.\n- Admissions (s81): Admissions by accused not excluded by hearsay.\n- Business records (s69): Routine records made in course of business.\n- Contemporaneous statements (s66A): About health, feelings, sensations, intention.\n- Other statutory carve-outs (ss70–75): Tags, labels, reputation, public rights, etc.\n## 4. Criminal-Specific Restrictions\nReliability checks: Jury warning under s165 (unreliable evidence). Must be cautious if source not cross-examinable.\nCase law: Kadir v The Queen (2020) 267 CLR 109 – reliability crucial where covert recordings admitted.\nB v The Queen (2012) – risk of undue weight.\n## 5. Exclusionary Discretions\nEven if exception applies, still test against:\n- s135 (general discretion) – probative value substantially outweighed by prejudice/confusion/waste.\n- s137 (criminal only) – mandatory exclusion if probative value outweighed by unfair prejudice.\nDupas v R (2012) – directions can mitigate prejudice.\n## 6. Exam Application Steps\n1. State that evidence is a previous representation → prima facie hearsay under s59.\n2. Identify purpose (truth of contents vs non-hearsay purpose, s60).\n3. Consider exceptions (s65 if unavailable, s66 if available, s69 business records, etc).\n4. Apply any discretionary or mandatory exclusions (s135/s137).\n5. Conclude on admissibility.\n## 7. Template Answer Sentence\n“The statement is a previous representation and is prima facie inadmissible as hearsay (s59). However, it may fall within the [s65/s66/etc] exception. Even if admissible under that exception, the Court must consider discretionary (s135) or mandatory (s137) exclusion. On balance, the evidence is [likely admissible/admissible subject to jury warning] because its probative value is high and any risk of unfair prejudice can be managed by directions (Dupas; Kadir).”"
  },
  {
    "title": "Hearsay s 65 — Exam Template (with Relevance)",
    "body": "## Exam Template: Hearsay (s 65) with Relevance\n## Step 1: Relevance (s 55)\nIssue: Is the evidence relevant?\nRule: Evidence is relevant if it could rationally affect the assessment of the probability of a fact in issue (s 55). Irrelevant evidence is inadmissible (s 56).\nApplication: The out-of-court statement goes to [fact in issue] (e.g., identification of accused, cause of injury, responsibility for fire). It could rationally affect the tribunal’s assessment.\nConclusion: The statement is relevant.\n## Step 2: Hearsay Rule (s 59)\nIssue: Is the statement hearsay?\nRule: A representation is hearsay if it is tendered to prove the truth of its content (s 59).\nApplication: The statement (“X did Y”) is tendered to prove that X did Y. This is hearsay.\nConclusion: Prima facie inadmissible unless an exception applies.\n## Step 3: Exception – s 65 (Unavailability in Criminal Proceedings)\nRule: Hearsay may be admitted if the maker is unavailable and one of the following gateways applies:\n- (a) Made under a duty to make representation\n- (b) Made when or shortly after the asserted fact occurred\n- (c) Made in circumstances making fabrication unlikely\n- (d) Made against maker’s interest\nMust also satisfy s 65(3) (personal knowledge) and not fall foul of s 65(8) (multiple hearsay).\n### Application (Admissible Example)\nFacts: Victim staggers into neighbour’s house minutes after stabbing and says “Tom stabbed me.”\nUnavailability: Victim deceased → unavailable.\nGateway:\n- s 65(2)(b): Made shortly after event.\n- s 65(2)(c): Circumstances (serious injury, distress, spontaneity) make fabrication unlikely.\nSafeguards: Victim clearly had personal knowledge (s 65(3)).\nConclusion: Fits s 65.\n### Application (Inadmissible Example)\nFacts: A week after the fire, victim told friend “Sarah admitted lighting the fire.” Victim now overseas (unavailable).\nUnavailability: Yes.\nGateway:\n- s 65(2)(a): No duty.\n- s 65(2)(b): Not shortly after → too remote.\n- s 65(2)(c): Casual conversation → fabrication possible.\n- s 65(2)(d): Not against interest.\nMultiple hearsay: Victim relays Sarah’s alleged confession → double hearsay. No exception for both layers.\nConclusion: Fails s 65.\n## Step 4: Discretionary Exclusion (ss 135, 137)\nEven if s 65 satisfied, court may exclude if:\n- Probative value is outweighed by danger of unfair prejudice (s 137 – criminal only).\n- Evidence may mislead/confuse or cause undue waste of time (s 135).\n## Final Conclusion\nIn Example 1 (stabbing) → admissible under s 65.\nIn Example 2 (arson gossip) → inadmissible hearsay.\n## Exam Technique\n1. Start with Relevance (always!).\n2. Identify Hearsay.\n3. Work through s 65 gateways systematically.\n4. Apply discretionary exclusions.\n5. Draw a clear conclusion (admissible vs inadmissible)."
  }
];
